# Generated by Django 5.1 on 2024-08-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieCd', models.IntegerField(primary_key=True, serialize=False)),
                ('movieNm', models.TextField()),
                ('movieNmEn', models.TextField()),
                ('prdtYear', models.FloatField()),
                ('openDt', models.FloatField()),
                ('typeNm', models.TextField()),
                ('prdtStatNm', models.TextField()),
                ('nationAlt', models.TextField()),
                ('genreAlt', models.TextField()),
                ('repNationNm', models.TextField()),
                ('repGenreNm', models.TextField()),
            ],
        ),
    ]
